server:
  port: 8082
spring:
  application:
    name: tech-challenge-orders
  data:
    mongodb:
      authentication-database: admin
      host: ${MONGO_HOST}
      port:
      database: tech-challenge-product
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}


  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
api:
  products:
    url: ${URL_PRODUCTS}
    path: api/v1/products/find
  customers:
    url: ${URL_CUSTOMERS}
    path: api/v1/customers/find
kafka:
  topic:
    produce:
      orders: tech.orders
    consumer:
      groupId: production
      production:
        status: status.order
