server:
  port: 8086
spring:
  application:
    name: tech-challenge-orders
  data:
    mongodb:
      authentication-database: admin
      #uri: mongodb://root:example@mongo-db/tech-challenge-orders?authSource=admin&replicaSet=myRepl
      #uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@{MONGO_HOST}/tech-challenge-orders
      host: 10.109.185.177
      port: 27017
      database: tech-challenge-orders
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}


  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
api:
  products:
    url: ${URL_PRODUCTS}
    path: api/v1/products/find
  customers:
    url: ${URL_CUSTOMERS}
    path: api/v1/customers/find
kafka:
  topic:
    produce:
      orders: tech.orders
    consumer:
      groupId: production
      production:
        status: status.order
