server:
  port: 8082
spring:
  application:
    name: tech-challenge-orders
  data:
    mongodb:
      authentication-database: admin
      host: ${MONGO_HOST}
      port:
      database: tech-challenge-orders
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}


  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
api:
  products:
    url: ${URL_PRODUCTS}
    path: api/v1/products/find
  customers:
    url: ${URL_CUSTOMERS}
    path: api/v1/customers/find
kafka:
  topic:
    produce:
      orders: tech.orders
    consumer:
      groupId: production
      production:
        status: status.order

logging:
  level:
    com.techchallenge.infrastructure.external.request:
      RequestCustomer: DEBUG

swagger:
  title: Microserviço de Pedidos
  contact:
    email: daniel.cor@outlook.com
    name: Daniel Aleixo Correa
    description: Microserviço desenvolvido para o curso de pós tech da FIAP
    version: 1.0