apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-production
  labels:
    app: tech-challenge-production
spec:
  type: LoadBalancer
  selector:
    app: tech-challenge-production
  ports:
    - protocol: TCP
      name: http
      port: 8082
      targetPort: 8082
      nodePort: 30006