apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
spec:
  type: NodePort
  selector:
    app: orders
  ports:
    - protocol: TCP
      name: http
      port: 8082
      targetPort: 8082
      nodePort: 30006